ecommerce/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    product_grid_view,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    product_detail_view
)
from coupons.views import AddCouponView
from refunds.views import RequestRefundView
app_name = 'ecommerce'

urlpatterns = [
    path('', product_grid_view, name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', product_detail_view,  name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('pages.urls')),
    path('',include('ecommerce.urls', namespace='ecommerce'))

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ecommerce/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from coupons.models import Coupon
from refunds.models import Refund

CATEGORY_CHOICES = (
    ('S', 'Sneakers'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'new'),
    ('S', 'sale'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()


    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("ecommerce:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("ecommerce:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("ecommerce:remove-from-cart", kwargs={
            'slug': self.slug
        })

class ProductReview(models.Model):
    item = models.ForeignKey(Item ,on_delete=models.CASCADE, related_name='reviews')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Review {} by {}'.format(self.body, self.name)

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'coupons.Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/elements/footer.html
{% load static%}
<footer class="page-footer text-center font-small mt-4">
  <div class="row">
    <div class="col-md-4 col-sm-12">
      <img src="{% static 'img/logo_white.svg' %}" width="120px" >
    </div>
    <div class="col-md-4 col-sm-12">
      <ul class="navbar-nav footer-nav nav-flex-icons">
        <li class="nav-item">
          <a href="{% url 'privacy-policy' %}" class="nav-link waves-effect">Privacy Policy</a>
        </li>
         <li class="nav-item">
          <a href="{% url 'refund-policy' %}" class="nav-link waves-effect">Refund Policy</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'terms-and-conditions' %}" class="nav-link waves-effect">Terms & Conditions</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'ecommerce:request-refund' %}" class="nav-link waves-effect">Request a Refund</a>
        </li>
      </ul>
    </div>
    <div class="col-md-4 col-sm-12">
       <div class="">
        <a href="https://www.facebook.com/" target="_blank">
          <i class="fab fa-facebook-f mr-3"></i>
        </a>
        <a href="https://github.com/delegacz" target="_blank">
          <i class="fab fa-github mr-3"></i>
        </a>
        <a href="https://www.instagram.com/deli_" target="_blank">
          <i class="fab fa-instagram mr-3"></i>
        </a>
      </div>
    </div>
  <div>
</footer>

templates/elements/navbar.html
{% load cart_template_tags %}
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <img src="{% static 'img/logo_black.svg' %}" width="120px" >
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'ecommerce:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/elements/pagination.html
{% if response.has_other_pages %}
    <ul class="pagination">
      {% if response.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ response.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
      {% else %}
        <li class="page-item disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in response.paginator.page_range %}
        {% if response.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if response.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ response.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
      {% else %}
        <li class="page-item disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
{% endif %}

templates/elements/product_filter_bar.html
{% load crispy_forms_tags %}      
      <!--Navbar-->
      <nav class="navbar navbar-expand-lg product-filter navbar-dark lighten-3 mt-3 mb-5">
        <!-- Navbar brand -->
        <!-- Collapsible content -->
        <div id="product-filter-from">
          <!-- Links -->
          <form method="GET">
            {{ filter.form|crispy }}
                <input class="nav-link" type="submit">
            </form>
          <!-- Links -->

        </div>
        <!-- Collapsible content -->
      </nav>
      <!--/.Navbar-->

templates/elements/product_grid.html
      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        <div class="row wow fadeIn">
          {% for item in response %}
          <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
              <div class="view overlay">
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <div class="card-body text-center">
                  <h5 class="category-name">{{ item.get_category_display }}</h5>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">{{item.get_label_display}}</span>
                    </a>
                  </strong>
                </h5>
                <h4 class="font-weight-bold blue-text">
                  <strong>€
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->
      {% include "elements/pagination.html" %}

templates/elements/product_review.html
{% load crispy_forms_tags %}
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ reviews.count }} Reviews</h2>

        {% for review in reviews %}
        <hr>
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ review.name }}
            <span class=" text-muted font-weight-normal">
              {{ review.created_on }}
            </span>
          </p>
          {{ review.body | linebreaks }}
        </div>
        
        {% endfor %}
      </div>
    </div>
    <div class="col-md-12 card mb-4  mt-3 ">
      <div class="card-body">

        <h3>Leave a review</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ review_form|crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>

      </div>
    </div>
  </div>
</div>

templates/elements/scripts.html
{% load static %}
  
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script  src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script  src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script src="{% static 'js/stripe.js' %}"></script>
<!-- Custom Scripts -->
<script src="{% static 'js/custom-scripts.js' %}"></script>